###########
# site.title
# host: 0.0.0.0
theme: minima
title: Jario 
name: Jario 
description: > # this means to ignore newlines until "baseurl:"
  Cursos Qaulifica DF .
permalink: ':title/'
#baseurl: "/linux.gitub.io" # the subpath of your site, e.g. /blog
#url: "https://logs.jar.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: jarioswami #if your site has a twitter account, enter it here

# Author Settings
author: Jario Swami # add your name
#author-img: avatar.png # add your photo
#about-author:  Jario estudo física, gestão ambiental e pedagogia na universidade. É mestre de yoga e defensor de um estilo de vida minimalista.
#google_analytics: G-0PV74153TH 

#########################
# more settings

plugins:
  - jekyll-paginate
  - jekyll-sitemap  
  - jekyll-feed
  - jekyll-redirect-from
    
whitelist:
  - jekyll-redirect-from

markdown: kramdown



permalink: /:slug
timezone: America/Sao_Paulo
future: false

exclude:
- README.md
- LICENSE.md

exclude: [vendor]

