theme: jekyll-theme-minimal
description: blog teste
logo: https://1.bp.blogspot.com/-8LP81QT7C9k/YALPsuMGvHI/AAAAAAAAkiE/gT2scvPbTZMnF-5-dvlEKDeUwVuUl5WdwCK4BGAYYCw/s1600/jarioblog.png
show_downloads: true
google_analytics: 
