title: Jario
e-mail: jario@outlook.com
theme: jekyll-theme-minimal 
description: Blog com pequenas informações sobre infomática, internet e demais assuntos TI
domain: git.jar.io 
baseurl: /jario.github.io/
production_url : https://git.jar.io
#logo: https://1.bp.blogspot.com/-8LP81QT7C9k/YALPsuMGvHI/AAAAAAAAkiE/gT2scvPbTZMnF-5-dvlEKDeUwVuUl5WdwCK4BGAYYCw/s1600/jarioblog.png
show_downloads: false
google_analytics: 
