title: Jario
e-mail: jario@outlook.com
theme: lanyon
description: Jario Swami é meu nome social. Sou mestre de yoga, consultor em meio ambiente e desenvolvimento sustentável. Notícias e Informações. Artigos sobre meu cotidiano referentes a tudo.
#logo: https://1.bp.blogspot.com/-8LP81QT7C9k/YALPsuMGvHI/AAAAAAAAkiE/gT2scvPbTZMnF-5-dvlEKDeUwVuUl5WdwCK4BGAYYCw/s1600/jarioblog.png
show_downloads: false
google_analytics: 
